[package]
name = "pingzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.30"
ping-rs = "0.1.2"
ssh2 = "0.9.4"
